apiVersion: apps/v1
kind: Deployment
metadata:
  name: coder
  namespace: coder
  labels:
    app: coder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coder
  template:
    metadata:
      labels:
        app: coder
    spec:
      serviceAccountName: coder
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: coder
        image: ghcr.io/coder/coder:v2.18.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        # PostgreSQL connection URL from secret
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-url
              key: url
        
        # Access URL - MUST match your ingress hostname
        - name: CODER_ACCESS_URL
          value: "http://code.homelab.com"
        
        # Wildcard access for workspace dev URLs (optional)
        - name: CODER_WILDCARD_ACCESS_URL
          value: "*.code.homelab.com"
        
        # Disable telemetry
        - name: CODER_TELEMETRY_ENABLE
          value: "false"
        
        # Enable Prometheus metrics
        - name: CODER_PROMETHEUS_ENABLE
          value: "true"
        
        # Trust proxy headers
        - name: CODER_PROXY_TRUSTED_HEADERS
          value: "X-Forwarded-For,X-Forwarded-Proto"
        - name: CODER_PROXY_TRUSTED_ORIGINS
          value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        
        # HTTP address
        - name: CODER_HTTP_ADDRESS
          value: "0.0.0.0:8080"
        
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        
        livenessProbe:
          httpGet:
            path: /api/v2/buildinfo
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        
        readinessProbe:
          httpGet:
            path: /api/v2/buildinfo
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder
  namespace: coder
  labels:
    app: coder
