apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: homarr
    meta.helm.sh/release-namespace: homarr
  labels:
    app.kubernetes.io/instance: homarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homarr
    app.kubernetes.io/version: v1.38.0
    helm.sh/chart: homarr-5.12.0
  name: homarr
  namespace: homarr
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: app
    port: 7575
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: homarr
    app.kubernetes.io/name: homarr
  sessionAffinity: None
  type: ClusterIP
