apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: distributed-ai-cluster
  namespace: kuberay-system
  labels:
    ray.io/cluster: distributed-ai-cluster
spec:
  # Ray version - use specific version for stability
  rayVersion: "2.9.0"
  
  # Enable autoscaling for dynamic workloads
  enableInTreeAutoscaling: true
  
  # Autoscaler configuration
  autoscalerOptions:
    # Scale down idle workers after 10 minutes (longer for big models)
    idleTimeoutSeconds: 600
    upscalingMode: Default
    resources:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"
  
  # Head node - minimal resources, control plane only
  headGroupSpec:
    serviceType: ClusterIP
    
    rayStartParams:
      dashboard-host: "0.0.0.0"
      # CRITICAL: Set to "0" to prevent task scheduling on head
      num-cpus: "0"
      # Head memory - enough for GCS and dashboard
      memory: "53687091200"  # 50GB in bytes
      metrics-export-port: "8080"
      # Optimize for large models
      object-store-memory: "21474836480"  # 20GB for head's object store
    
    template:
      metadata:
        labels:
          component: ray-head
          workload: distributed-ai
      spec:
        # Node affinity to spread across servers
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: component
                        operator: In
                        values:
                          - ray-head
                          - ray-worker
                  topologyKey: kubernetes.io/hostname
        
        containers:
          - name: ray-head
            image: rayproject/ray:2.9.0
            imagePullPolicy: IfNotPresent
            
            # Head resources - control plane operations
            resources:
              limits:
                cpu: "16"
                memory: "50Gi"
              requests:
                cpu: "16"
                memory: "50Gi"
            
            ports:
              - containerPort: 6379
                name: gcs
                protocol: TCP
              - containerPort: 8265
                name: dashboard
                protocol: TCP
              - containerPort: 10001
                name: client
                protocol: TCP
              - containerPort: 8080
                name: metrics
                protocol: TCP
            
            # Health checks
            livenessProbe:
              httpGet:
                path: /api/version
                port: 8265
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 10
              failureThreshold: 3
            
            readinessProbe:
              httpGet:
                path: /api/version
                port: 8265
              initialDelaySeconds: 15
              periodSeconds: 10
              timeoutSeconds: 5
            
            # Graceful shutdown
            lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh", "-c", "ray stop"]
            
            # Environment for monitoring integration
            env:
              - name: RAY_GRAFANA_HOST
                value: "http://grafana.monitoring.svc:3000"
              - name: RAY_PROMETHEUS_HOST
                value: "http://prometheus.monitoring.svc:9090"
              # Memory management for large models
              - name: RAY_memory_monitor_refresh_ms
                value: "250"
            
            # Shared memory for object store
            volumeMounts:
              - name: dshm
                mountPath: /dev/shm
        
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 20Gi
  
  # Worker group - MAXIMIZED for distributed AI workloads
  workerGroupSpecs:
    - groupName: ai-workers
      # Start with 2 workers, can scale 0-3
      replicas: 2
      minReplicas: 0
      maxReplicas: 3
      
      rayStartParams:
        # Workers use full resources - auto-detected from limits
        metrics-export-port: "8080"
        # Large object store for model weights and tensors
        object-store-memory: "107374182400"  # 100GB per worker
      
      template:
        metadata:
          labels:
            component: ray-worker
            workload: distributed-ai
            model-inference: "enabled"
        spec:
          # CRITICAL: Spread workers across different nodes
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: component
                        operator: In
                        values:
                          - ray-worker
                  topologyKey: kubernetes.io/hostname
          
          # Prioritize these pods
          priorityClassName: system-node-critical
          
          containers:
            - name: ray-worker
              image: rayproject/ray:2.9.0
              imagePullPolicy: IfNotPresent
              
              # MAXIMIZED resources for 357B model distribution
              # Each worker gets 58 cores and 220GB RAM
              resources:
                limits:
                  cpu: "58"
                  memory: "220Gi"
                requests:
                  cpu: "58"
                  memory: "220Gi"
              
              ports:
                - containerPort: 8080
                  name: metrics
                  protocol: TCP
              
              # Health monitoring
              livenessProbe:
                tcpSocket:
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 30
                timeoutSeconds: 10
                failureThreshold: 5
              
              # Graceful shutdown with extended timeout for large models
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh", "-c", "ray stop"]
              
              # Environment optimizations for large AI models
              env:
                # Memory management
                - name: RAY_memory_monitor_refresh_ms
                  value: "250"
                # Object spilling for memory pressure
                - name: RAY_object_spilling_config
                  value: '{"type":"filesystem","params":{"directory_path":"/tmp/ray"}}'
                # Optimize for large objects
                - name: RAY_max_direct_call_object_size
                  value: "100000000"  # 100MB
                # Plasma store configuration
                - name: RAY_plasma_store_socket_name
                  value: "/tmp/ray/plasma_store"
              
              # Large shared memory for object store
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: ray-temp
                  mountPath: /tmp/ray
          
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                # 100GB shared memory per worker for model weights
                sizeLimit: 100Gi
            - name: ray-temp
              emptyDir:
                sizeLimit: 50Gi  # Spillover storage
