apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: excalidraw
    meta.helm.sh/release-namespace: local-cloud
  labels:
    app.kubernetes.io/instance: excalidraw
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: excalidraw
    app.kubernetes.io/version: v0.15.0
    helm.sh/chart: excalidraw-0.1.1
  name: excalidraw-headless
  namespace: local-cloud
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: excalidraw
    app.kubernetes.io/name: excalidraw
  sessionAffinity: None
  type: ClusterIP
