apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    tailscale.com/managed: 'true'
    tailscale.com/parent-resource: kube-dns
    tailscale.com/parent-resource-ns: kube-system
    tailscale.com/parent-resource-type: svc
  name: ts-kube-dns-crlgk
  namespace: tailscale
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: 9251ffd1-ef07-4207-add6-8adac4432092
  serviceName: ts-kube-dns-crlgk
  template:
    metadata:
      annotations:
        tailscale.com/operator-last-set-cluster-ip: 10.96.0.10
      deletionGracePeriodSeconds: 10
      labels:
        app: 9251ffd1-ef07-4207-add6-8adac4432092
        tailscale.com/managed: 'true'
        tailscale.com/parent-resource: kube-dns
        tailscale.com/parent-resource-ns: kube-system
        tailscale.com/parent-resource-type: svc
    spec:
      containers:
      - env:
        - name: TS_USERSPACE
          value: 'false'
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: TS_KUBE_SECRET
          value: $(POD_NAME)
        - name: TS_EXPERIMENTAL_VERSIONED_CONFIG_DIR
          value: /etc/tsconfig/$(POD_NAME)
        - name: TS_DEBUG_FIREWALL_MODE
          value: auto
        - name: TS_DEST_IP
          value: 10.96.0.10
        - name: TS_INTERNAL_APP
          value: k8s-operator-ingress-proxy
        image: tailscale/tailscale:v1.88.2
        imagePullPolicy: Always
        name: tailscale
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tsconfig/ts-kube-dns-crlgk-0
          name: tailscaledconfig-0
          readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - sysctl -w net.ipv4.ip_forward=1 && if sysctl net.ipv6.conf.all.forwarding;
          then sysctl -w net.ipv6.conf.all.forwarding=1; fi
        command:
        - /bin/sh
        - -c
        image: tailscale/tailscale:v1.88.2
        imagePullPolicy: IfNotPresent
        name: sysctler
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: proxies
      serviceAccountName: proxies
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tailscaledconfig-0
        secret:
          defaultMode: 420
          secretName: ts-kube-dns-crlgk-0
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
