apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-training-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 500Gi
