apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nextcloud
    meta.helm.sh/release-namespace: local-cloud
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/version: 11.4.6
    helm.sh/chart: mariadb-20.5.5
  name: nextcloud-mariadb-headless
  namespace: nextcloud
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: mariadb
  sessionAffinity: None
  type: ClusterIP
