---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-mariadb
  namespace: local-cloud
spec:
  encryptedData:
    mariadb-password: AgB6Un8Y8Wlyh2J0EgIMH52qRotQbVrhdd+/KaDIyoaQ5wzhs8oKb3+XWMeHkehgO2qSQFcrG9KGEdFyh7UP1YA1e47L89I4h4966LU35pBw+TB6qmCtxZ7r0K2GnGp1ERdgSsn+rdoP94ZGjvrXlDDm7GT1p8BEqhtegYg7bPKOazKHMgVUBPy/ZVDsfTWD0DV4RCHn62OkIbi7OMKAE8CDkGUsWUOU8PR7BR7KSSkSoPWVsMKYumcBd3z71G3ziuL7YJHFgvp+8VsrVXd/jnTzZz6utRrBbZUSKLIBKAHmHxGWBWhWsI8997TjnyEl+WIX6Qb/C2h7ZC3DQjbP6O/SJ2tHAZOI8LK3Zj/Ud6P5nbXbsPjM5aplEFc5O+/YHado19QDRfULCjaqnPU14opzo+CzmiCoK5AIqcxeD7eQ5p1iTFivaifoWO24FzYu+pFk51Xx98y7IFCFPwNh11X+bOdWct9Yo9stCoDudvNp3wC/3+3Gd8279J59+rk4CodhtXsK5VBEBQpCFG8vtKetCFmJWyEa4HCk66DsM69x+WhGebNEZtX8yTQ4QK32zYGMSmG3sC0oTd8OXmA0LLh1T/CxYB1X1hdmJkjmNVhtnndounmSYmfsxEO9WWsBEszg6MZHEaXLX9O/rjQ6P0gdoQFpRJ4Ff4GcWtJAWXsbyVQiRGf54/uQRfpSok39tXKTZRGNFa53tL89dmYbtud6KYl9h6aShTMDi0u296SFiw==
    mariadb-root-password: AgCaJO8Yq/TZE9X48ExB/AkqyEWgWaPiMIBAU01HogzPG+AIvfFbwwZ4nwnKD73nPgcOSdQKPviSviFL4W4i5o6STJhmp1SKpmu2ZRNfRV/MB7X/d9P9AKcYzUP9vziKq/uvo/s6kqczEGrFiBz43qKQ2XVaoUVYiAG7CZ0KRQcEJVN87b9j7FUaWckq66kBCC1/BPYpceFJXOqSiMGR/vPeXuXFwa7OSB/706L2pBCJVJ+pkVK5eka4SNYf9P4pQuhL01f1D4ybNUvnTZdJoYfEpevF2TVg76yEKr3jhBgzA0zBmw7Wca4S/Dh8/sN6twtooxenqLhO/BbP6VQh8qC61k5kCG5Yp2ipWTEAWvlgDBeVyjiaVCEnub03d8Tv+royebi05msJEuwD1rrg9rkekw3WEApNKaThD2TzgVGwp3KPUpWVj2E7QlNLkaFOsAUXLPgLA/1G7AXmeFVlkB7GouOsWDOo81dkqOXhi3bzR8KWAcmIlbDHM1965QiEhWgecWqiujTFgvctvjseRP52CA1yRO+IYulAFheO/ru3A3C5GRikHR0i8bzY0Z6GXaytRJoSSl1UHfBXaQ3TxU8vmSfWxi2DUwmN7etK9NTIW0SIkXARew9pAywTeTdOWIZLm8jfit2IKQiW+NodDCdQqUKkJMwAwAo9quyoqYI0DzS3O4D+sm+66GbTWP1SceLf8GYFSmvwxBBpn+LvBdUYtSJRDPZDIosHskU1smMnzQ==
  template:
    metadata:
      name: nextcloud-mariadb
      namespace: local-cloud
