apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-mariadb
  namespace: local-cloud
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: nextcloud
data:
  my.cnf: '[mysqld]

    skip-name-resolve

    explicit_defaults_for_timestamp

    basedir=/opt/bitnami/mariadb

    datadir=/bitnami/mariadb/data

    socket=/opt/bitnami/mariadb/tmp/mysql.sock

    tmpdir=/opt/bitnami/mariadb/tmp

    max_allowed_packet=16M

    bind-address=*

    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

    log-error=/opt/bitnami/mariadb/logs/mysqld.log


    [client]

    socket=/opt/bitnami/mariadb/tmp/mysql.sock

    default-character-set=UTF8

    plugin_dir=/opt/bitnami/mariadb/plugin


    [manager]

    socket=/opt/bitnami/mariadb/tmp/mysql.sock

    '
