apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-redis-health
  namespace: local-cloud
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: nextcloud
data:
  ping_liveness_local.sh: |
    #!/bin/bash
    # Read password from secret
    REDIS_PASSWORD=$(cat /opt/bitnami/redis/secrets/redis-password)
    response=$(redis-cli -h localhost -p 6379 -a "$REDIS_PASSWORD" ping)
    if [ "$response" != "PONG" ]; then
      exit 1
    fi
  ping_readiness_local.sh: |
    #!/bin/bash
    # Read password from secret
    REDIS_PASSWORD=$(cat /opt/bitnami/redis/secrets/redis-password)
    response=$(redis-cli -h localhost -p 6379 -a "$REDIS_PASSWORD" ping)
    if [ "$response" != "PONG" ]; then
      exit 1
    fi
  ping_liveness_local_and_master.sh: |
    #!/bin/bash
    script_dir="$(dirname "$0")"
    exit_status=0
    # Check local Redis
    "$script_dir/ping_liveness_local.sh" $1 || exit_status=$?
    # Check master Redis
    "$script_dir/ping_liveness_master.sh" $1 || exit_status=$?
    exit $exit_status
  ping_readiness_local_and_master.sh: |
    #!/bin/bash
    script_dir="$(dirname "$0")"
    exit_status=0
    # Check local Redis
    "$script_dir/ping_readiness_local.sh" $1 || exit_status=$?
    # Check master Redis  
    "$script_dir/ping_readiness_master.sh" $1 || exit_status=$?
    exit $exit_status
  ping_liveness_master.sh: |
    #!/bin/bash
    # Read password from secret
    REDIS_PASSWORD=$(cat /opt/bitnami/redis/secrets/redis-password)
    response=$(redis-cli -h "$REDIS_MASTER_HOST" -p "$REDIS_MASTER_PORT_NUMBER" -a "$REDIS_PASSWORD" ping)
    if [ "$response" != "PONG" ]; then
      exit 1
    fi
  ping_readiness_master.sh: |
    #!/bin/bash
    # Read password from secret
    REDIS_PASSWORD=$(cat /opt/bitnami/redis/secrets/redis-password)
    response=$(redis-cli -h "$REDIS_MASTER_HOST" -p "$REDIS_MASTER_PORT_NUMBER" -a "$REDIS_PASSWORD" ping)
    if [ "$response" != "PONG" ] && [ "$response" != "LOADING Redis is loading the dataset in memory" ]; then
      exit 1
    fi
