apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: open-webui
    meta.helm.sh/release-namespace: ollama
  labels:
    app.kubernetes.io/component: open-webui-pipelines
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pipelines
    app.kubernetes.io/version: alpha
    helm.sh/chart: pipelines-0.9.0
  name: open-webui-pipelines
  namespace: ollama
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9099
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: open-webui-pipelines
    app.kubernetes.io/instance: open-webui
  sessionAffinity: None
  type: ClusterIP
