apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: open-webui
    meta.helm.sh/release-namespace: ollama
  labels:
    app.kubernetes.io/component: open-webui
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/version: 0.6.30
    helm.sh/chart: open-webui-8.6.0
  name: open-webui
  namespace: ollama
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: open-webui
      app.kubernetes.io/instance: open-webui
  serviceName: open-webui
  template:
    metadata:
      labels:
        app.kubernetes.io/component: open-webui
        app.kubernetes.io/instance: open-webui
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: open-webui
        app.kubernetes.io/version: 0.6.30
        helm.sh/chart: open-webui-8.6.0
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: OLLAMA_BASE_URLS
          value: http://open-webui-ollama.ollama.svc.cluster.local:11434
        - name: OPENAI_API_BASE_URLS
          value: http://open-webui-pipelines.ollama.svc.cluster.local:9099;https://api.openai.com/v1;http://vllm-api.kuberay-system.svc.cluster.local:8000/v1
        - name: OPENAI_API_KEYS
          value: ";sk-openai-key;sk-vllm-dummy"
        - name: WEBUI_HOST
          value: 0.0.0.0
        image: ghcr.io/open-webui/open-webui:0.6.30
        imagePullPolicy: IfNotPresent
        name: open-webui
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /app/backend/data
          name: data
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      initContainers:
      - command:
        - sh
        - -c
        - cp -R -n /app/backend/data/* /tmp/app-data/
        image: ghcr.io/open-webui/open-webui:0.6.30
        imagePullPolicy: IfNotPresent
        name: copy-app-data
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/app-data
          name: data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: open-webui
      serviceAccountName: open-webui
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: open-webui
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
