apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: open-webui
    meta.helm.sh/release-namespace: ollama
  labels:
    app.kubernetes.io/component: open-webui-ollama
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ollama
    app.kubernetes.io/version: 0.11.11
    helm.sh/chart: ollama-1.29.0
  name: open-webui-ollama
  namespace: ollama
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 11434
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: open-webui-ollama
    app.kubernetes.io/instance: open-webui
  sessionAffinity: None
  type: ClusterIP
