apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pvc-storage-alerts
  namespace: monitoring
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
spec:
  groups:
  - name: pvc-capacity
    interval: 30s
    rules:
    - alert: PVCUsageHigh
      expr: |
        (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PVC {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} is {{ $value | humanizePercentage }} full"
        description: "Volume usage has exceeded 85%. Consider cleanup or expansion."
    
    - alert: PVCUsageCritical
      expr: |
        (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) > 0.95
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "CRITICAL: PVC {{ $labels.persistentvolumeclaim }} at {{ $value | humanizePercentage }} capacity"
        description: "Volume nearly full. Immediate action required to prevent application failures."
    
    - alert: PVCWillFillIn4Days
      expr: |
        predict_linear(kubelet_volume_stats_available_bytes[6h], 4 * 24 * 3600) < 0
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: "PVC {{ $labels.persistentvolumeclaim }} will be full in 4 days"
        description: "Based on current growth trends, this volume will be full in approximately 4 days."
    
    - alert: NodeDiskPressure
      expr: |
        kube_node_status_condition{condition="DiskPressure",status="true"} == 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Node {{ $labels.node }} experiencing disk pressure"
        description: "Kubelet is evicting pods due to disk space constraints on this node."
    
    - alert: InodeUsageHigh
      expr: |
        (kubelet_volume_stats_inodes_used / kubelet_volume_stats_inodes) > 0.90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Inode usage high on PVC {{ $labels.persistentvolumeclaim }}"
        description: "Inode usage is at {{ $value | humanizePercentage }}. May cause disk pressure even with free space."
