apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.gitlab.io
    chart: gitlab
    targetRevision: 9.5.1
    helm:
      releaseName: gitlab
      valuesObject:
        # Force the upgrade check to pass - this is a fresh install
        upgradeCheck:
          enabled: false
        
        gitlab:
          gitaly:
            persistence:
              storageClass: local-path
              size: 10Gi
        
        gitlab-runner:
          install: false
        
        global:
          hosts:
            domain: homelab.com
            https: false
          ingress:
            class: nginx
            configureCertmanager: false
            tls:
              enabled: false
        
        minio:
          persistence:
            storageClass: local-path
            size: 10Gi
        
        nginx-ingress:
          enabled: false
        
        postgresql:
          primary:
            persistence:
              storageClass: local-path
              size: 10Gi
        
        redis:
          master:
            persistence:
              storageClass: local-path
              size: 1Gi
        
        prometheus:
          install: true
          server:
            persistentVolume:
              storageClass: local-path
              size: 5Gi
