apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote-desktop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KylerRussell/k8s-gitops.git
    targetRevision: main
    path: apps/manifests/remote-desktop
  destination:
    server: https://kubernetes.default.svc
    namespace: remote-desktop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
