apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firecrawl
resources:
  - firecrawl-redis.yaml
  - firecrawl-rabbitmq.yaml
  - firecrawl-postgres.yaml
  - firecrawl-playwright.yaml
  - firecrawl-api.yaml
  - firecrawl-ingress.yaml
